EntertainNetBitirme/Controllers/WriterPanelContentController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EntertainNetBitirme.Controllers
{
    public class WriterPanelContentController : Controller
    {
        ContentManager cm = new ContentManager(new EfContentDal());

        HeadingManager hm = new HeadingManager(new EfHeadingDal());

        CategoryManager ctm = new CategoryManager(new EfCategoryDal());

        public ActionResult MyContents(string p)
        {
            Context c = new Context();
            p = (string)Session["writerMail"];
            var writerIdInfo = c.Writers.Where(x=>x.writerMail == p).Select(y=> y.writerId).FirstOrDefault();
            var contentValues = cm.GetListByWriter(writerIdInfo);
            return View(contentValues);
        }

        [HttpGet]
        public ActionResult AddContent() 
        {
            List<SelectListItem> valueCategory = (from x in ctm.GetList()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.categoryName,
                                                      Value = x.categoryId.ToString()
                                                  }).ToList();

            List<SelectListItem> valueHeading = (from x in hm.GetList()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.headingName,
                                                      Value = x.headingId.ToString()
                                                  }).ToList();
            ViewBag.vlc = valueCategory;
            ViewBag.vlh = valueHeading;

            return View();
        }

        [HttpPost]
        public ActionResult AddContent(Content p) 
        {
            Context c = new Context();
            string mail = (string)Session["writerMail"];
            var writerIdInfo = c.Writers.Where(x => x.writerMail == mail).Select(y => y.writerId).FirstOrDefault();
            p.contentDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            p.writerId = writerIdInfo;
            p.contentStatus = true;
            cm.ContentAdd(p);
            return RedirectToAction("MyContents");
        }
    }
}

EntertainNetBitirme/Views/WriterPanelContent/AddContent.cshtml
@model EntityLayer.Concrete.Content

@{
    ViewBag.Title = "AddContent";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<h1>İnceleme Ekleme</h1>
<br />
@using (Html.BeginForm("AddContent", "WriterPanelContent", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Başlık")
        @Html.DropDownListFor(x => x.headingId, (List<SelectListItem>)ViewBag.vlh, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.headingId)
        <br />
        @Html.Label("Yazı")
        @Html.TextAreaFor(x => x.contentValue, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.contentValue)
        <br />
        <button class="btn btn-success">Kaydet</button>
    </div>
}

EntertainNetBitirme/Views/WriterPanelContent/MyContents.cshtml
@using EntityLayer.Concrete
@model List<Content>

@{
    ViewBag.Title = "MyContents";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">
    <a href="/WriterPanelContent/AddContent" class="btn btn-info">Yeni İnceleme</a>
    <!-- Site wrapper -->
    <div class="wrapper">

        <section class="content">
            <div class="container-fluid">
                <!-- Timelime example  -->
                <div class="row">
                    <div class="col-md-12">
                        <!-- The time line -->
                        <div class="timeline">
                            <!-- timeline time label -->

                            @foreach (var item in Model)
                            {
                                <br />
                                <div class="time-label">
                                    <span class="bg-success">@(((DateTime)item.contentDate).ToString("dd MMMMMMM yyyy"))</span>

                                </div>
                                <!-- /.timeline-label -->
                                <!-- timeline item -->
                                <div>
                                    <i class="fas fa-comment bg-yellow"></i>
                                    <div class="timeline-item">
                                        <h3 class="timeline-header"><a href="#">@item.Heading.headingName</a></h3>
                                        <div class="timeline-body">
                                            @item.contentValue
                                        </div>
                                    </div>
                                </div>
                                <!-- END timeline item -->
                            }
                        </div>
                    </div>
                    <!-- /.col -->
                </div>
            </div>
            <!-- /.timeline -->
        </section>
        <!-- /.content -->
    </div>
    <!-- ./wrapper -->
</body>
</html>