EntertainNetBitirme/Controllers/AdminCategoryController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EntertainNetBitirme.Controllers
{
    public class AdminCategoryController : Controller
    {
        CategoryManager cm = new CategoryManager(new EfCategoryDal());

        public ActionResult Index()
        {
            var categoryValues = cm.GetList();
            return View(categoryValues);
        }

        [HttpGet]
        public ActionResult AddCategory() 
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddCategory(Category p) 
        {
            CategoryValidator categoryValidator = new CategoryValidator();
            ValidationResult results = categoryValidator.Validate(p);
            if (results.IsValid) 
            {
                cm.CategoryAdd(p);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }

        public ActionResult DeleteCategory(int id) 
        {
            var categoryValue = cm.GetById(id);
            cm.CategoryDelete(categoryValue);
            return RedirectToAction("Index");   
        }

        [HttpGet]
        public ActionResult UpdateCategory(int id) 
        {
            var categoryValue = cm.GetById(id);
            return View(categoryValue);
        }

        [HttpPost]
        public ActionResult UpdateCategory(Category p) 
        {
            cm.CategoryUpdate(p);
            return RedirectToAction("Index");
        }
    }
}

EntertainNetBitirme/Views/AdminCategory/AddCategory.cshtml
@model EntityLayer.Concrete.Category

@{
    ViewBag.Title = "AddCategory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Yeni Kategori Ekleme Sayfası</h1>
<br />

@using (Html.BeginForm("AddCategory", "AdminCategory", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Kategori Adı")
        @Html.TextBoxFor(x => x.categoryName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.categoryName)
        <br /> <br />
        @Html.Label("Kategori Açıklaması")
        @Html.TextAreaFor(x => x.categoryDescription, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.categoryDescription)
        <br /><br />
        <button class="btn btn-success">Kaydet</button>
    </div>
}

EntertainNetBitirme/Views/AdminCategory/Index.cshtml
@using EntityLayer.Concrete
@model List<Category>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<table class="table table-bordered">
    <tr>
        @*@<th>#</th>*@
        <th>Kategori Adı</th>
        <th>Durum</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Başlıklar</th>
    </tr>
    <tr>
        @foreach (var item in Model)
        {
        <tr>
            @*<th>@item.categoryId</th>*@
            <td>@item.categoryName</td>
            <td>@item.categoryStatus</td>
            <td><a href="/AdminCategory/DeleteCategory/@item.categoryId" class="btn btn-danger">Sil</a></td>
            <td><a href="/AdminCategory/UpdateCategory/@item.categoryId" class="btn btn-warning">Güncelle</a></td>
            <td><a href="#" class="btn btn-primary">Başlıklar</a></td>
        </tr>
        }
            </table>
        <a href="/AdminCategory/AddCategory" class="btn btn-info">Yeni Kategori</a>

EntertainNetBitirme/Views/AdminCategory/UpdateCategory.cshtml
@model EntityLayer.Concrete.Category

@{
    ViewBag.Title = "UpdateCategory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2>Kategori Güncelleme Sayfası</h2>
@using (Html.BeginForm("UpdateCategory","AdminCategory", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Kategori ID")
        @Html.TextBoxFor(x => x.categoryId, new { @class = "form-control" })
        <br />
        @Html.Label("Kategori Adı")
        @Html.TextBoxFor(x => x.categoryName, new { @class = "form-control" })
        <br />
        @Html.Label("Kategori Açıklaması")
        @Html.TextAreaFor(x => x.categoryDescription, new { @class = "form-control" })
        <br />
        <button class="btn btn-success">Değişiklikleri Kaydet</button>
    </div>
}