EntertainNetBitirme/Controllers/WriterPanelController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EntertainNetBitirme.Controllers
{
    public class WriterPanelController : Controller
    {
        HeadingManager hm = new HeadingManager(new EfHeadingDal());

        CategoryManager cm = new CategoryManager(new EfCategoryDal());

        WriterManager wm = new WriterManager(new EfWriterDal());

        WriterValidator writerValidator = new WriterValidator();

        Context c = new Context();

        [HttpGet]
        public ActionResult WriterProfile(int id = 0)
        {
            string p = (string)Session["writerMail"];
            id = c.Writers.Where(x => x.writerMail == p).Select(y => y.writerId).FirstOrDefault();
            var writerValue = wm.GetById(id);
            ViewBag.a = id;
            return View(writerValue);
        }

        [HttpPost]
        public ActionResult WriterProfile(Writer p)
        {
            ValidationResult results = writerValidator.Validate(p);
            if (results.IsValid)
            {
                wm.WriterUpdate(p);
                return RedirectToAction("MyHeadings");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }

        public ActionResult MyHeadings(string p) 
        {
            p = (string)Session["writerMail"];
            var writerIdInfo = c.Writers.Where(x => x.writerMail == p).Select(y => y.writerId).FirstOrDefault();
            var values = hm.GetListByWriter(writerIdInfo);
            return View(values);
        }

        [HttpGet]
        public ActionResult NewHeading()
        {
            List<SelectListItem> valueCategory = (from x in cm.GetList()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.categoryName,
                                                      Value = x.categoryId.ToString()
                                                  }).ToList();

            ViewBag.vlc = valueCategory;
            return View();
        }

        [HttpPost]
        public ActionResult NewHeading(Heading p) 
        {
            string mail = (string)Session["writerMail"];
            var writerIdInfo = c.Writers.Where(x => x.writerMail == mail).Select(y => y.writerId).FirstOrDefault();
            p.headingDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            p.writerId = writerIdInfo;
            p.headingStatus = true;
            hm.HeadingAdd(p);
            return RedirectToAction("MyHeadings");
        }

        [HttpGet]
        public ActionResult EditHeading(int id)
        {
            List<SelectListItem> valueCategory = (from x in cm.GetList()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.categoryName,
                                                      Value = x.categoryId.ToString()
                                                  }).ToList();

            ViewBag.vlc = valueCategory;

            var headingValue = hm.GetById(id);
            return View(headingValue);
        }

        [HttpPost]
        public ActionResult EditHeading(Heading p)
        {
            p.headingStatus = true;
            hm.HeadingUpdate(p);
            return RedirectToAction("MyHeadings");
        }

        public ActionResult DeleteHeading(int id)
        {
            var headingValue = hm.GetById(id);
            headingValue.headingStatus = false;
            hm.HeadingDelete(headingValue);
            return RedirectToAction("MyHeadings");
        }
    }
}

EntertainNetBitirme/Views/WriterPanel/EditHeading.cshtml
@model EntityLayer.Concrete.Heading

@{
    ViewBag.Title = "EditHeading";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<h2>Başlık Güncelleme</h2>
@using (Html.BeginForm("EditHeading", "WriterPanel", FormMethod.Post))
{
    <div class="form-group">
        @Html.HiddenFor(x => x.headingId)
        @Html.HiddenFor(x => x.writerId)
        @Html.HiddenFor(x => x.headingDate)
        @Html.HiddenFor(x => x.categoryId)
        @Html.Label("Başlık Adı")
        @Html.TextBoxFor(x => x.headingName, new { @class = "form-control" })
        <br />
        @*@Html.Label("Kategori")
        @Html.DropDownListFor(x => x.categoryId, (List<SelectListItem>)ViewBag.vlc, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.categoryId)
        <br />*@
        <button class="btn btn-success">Değişiklikleri Kaydet</button>
    </div>
}

EntertainNetBitirme/Views/WriterPanel/MyHeadings.cshtml
@using EntityLayer.Concrete
@model List<Heading>

@{
    ViewBag.Title = "MyHeadings";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

@{string color = "";}

<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Başlıklar</h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Başlık İşlemleri</h3>

                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                        <tr>
                            <th style="width: 1%">
                                #
                            </th>
                            <th style="width: 20%">
                                Başlık Adı
                            </th>
                            <th style="width: 30%">
                                Oluşturan Yazar
                            </th>
                            <th style="width: 8%" class="text-center">
                                Kategori
                            </th>
                            <th style="width: 20%">
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            if (item.Category.categoryName == "Dizi")
                            {
                                color = "badge badge-success";
                            }
                            if (item.Category.categoryName == "Oyun")
                            {
                                color = "badge badge-danger";
                            }
                            if (item.Category.categoryName == "Film")
                            {
                                color = "badge badge-info";
                            }
                            if (item.Category.categoryName == "Kitap")
                            {
                                color = "badge badge-secondary";
                            }
                            <tr>
                                <th>
                                    @item.headingId
                                </th>
                                <td>
                                    <a>
                                        @item.headingName
                                    </a>
                                    <br />
                                    <small>
                                        @(((DateTime)item.headingDate).ToString("dd MMMMMMM yyyy"))
                                    </small>
                                </td>
                                <td>
                                    <ul class="list-inline">
                                        <li class="list-inline-item">
                                            <img alt="Avatar" class="table-avatar" src="@item.Writer.writerImage">
                                            @item.Writer.writerName @item.Writer.writerSurName
                                        </li>
                                    </ul>
                                </td>
                                <td class="project-state">
                                    <span class="@color">@item.Category.categoryName</span>
                                </td>
                                <td class="project-actions text-right">
                                    <a class="btn btn-primary btn-sm" href="/Content/ContentByHeading/@item.headingId">
                                        <i class="fas fa-folder">
                                        </i>
                                        İncelemeler
                                    </a>
                                    <a class="btn btn-info btn-sm" href="/WriterPanel/EditHeading/@item.headingId">
                                        <i class="fas fa-pencil-alt">
                                        </i>
                                        Düzenle
                                    </a>
                                    <a class="btn btn-danger btn-sm" href="/WriterPanel/DeleteHeading/@item.headingId">
                                        <i class="fas fa-trash">
                                        </i>
                                        Sil
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->

    </section>
    <!-- /.content -->
    <!-- Control Sidebar -->
    <!-- /.control-sidebar -->
    <a href="/WriterPanel/NewHeading" class="btn btn-info">Yeni Başlık</a>
</body>
</html>

EntertainNetBitirme/Views/WriterPanel/NewHeading.cshtml
@model EntityLayer.Concrete.Heading

@{
    ViewBag.Title = "NewHeading";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<h1>Başlık Ekleme</h1>
<br />
@using (Html.BeginForm("NewHeading", "WriterPanel", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Başlık Adı")
        @Html.TextBoxFor(x => x.headingName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.headingName)
        <br />
        @Html.Label("Kategori")
        @Html.DropDownListFor(x => x.categoryId, (List<SelectListItem>)ViewBag.vlc, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.categoryId)
        <br />
        <button class="btn btn-success">Kaydet</button>
    </div>
}

EntertainNetBitirme/Views/WriterPanel/WriterProfile.cshtml
@model EntityLayer.Concrete.Writer

@{
    ViewBag.Title = "WriterProfile";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<h2>Profil Düzenleme</h2>

@using (Html.BeginForm("WriterProfile", "WriterPanel", FormMethod.Post))
{
    <div class="form-group">

        @*@Html.Label("Yazar ID")*@
        @Html.HiddenFor(x => x.writerId, new { @class = "form-control" })
        @Html.Label("Yazar Adı")
        @Html.TextBoxFor(x => x.writerName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.writerName)
        <br />
        @Html.Label("Yazar Soyadı")
        @Html.TextBoxFor(x => x.writerSurName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.writerSurName)
        <br />
        @Html.Label("Yazar Mail")
        @Html.TextBoxFor(x => x.writerMail, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.writerMail)
        <br />
        @Html.Label("Yazar Şifresi")
        @Html.TextBoxFor(x => x.writerPassword, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.writerPassword)
        <br />
        @Html.Label("Yazar Görsel Linki")
        @Html.TextBoxFor(x => x.writerImage, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.writerImage)
        <br />
        @Html.Label("Yazar Ünvan")
        @Html.TextBoxFor(x => x.writerTitle, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.writerTitle)
        <br />
        @Html.Label("Yazar Hakkında")
        @Html.TextAreaFor(x => x.writerAbout, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.writerAbout)
        <br />
        <button class="btn btn-success">Değişiklikleri Kaydet</button>
    </div>
}